// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxzofgsjyysvfxofnpey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4em9mZ3NqeXlzdmZ4b2ZucGV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTY2MTcsImV4cCI6MjA3MjI5MjYxN30.HYs5xp7oP__KBHOY4iEfAyPj3Dn0Ppjj8g6ZtMISfz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  // auth: {
  //   storage: localStorage,
  //   persistSession: true,
  //   autoRefreshToken: true,
  // }
});