import { MemberRole } from '@/prisma/client';
import { PERMISSIONS, PermissionString } from './constants';

export const MEMBER_ROLE_PERMISSIONS: Record<MemberRole, PermissionString[]> = {
  OWNER: [
    // Owners get almost everything, effectively a wildcard but explicitly listed is safer.
    ...Object.values(PERMISSIONS), // Or list them explicitly for safety
  ],
  ADMIN: [
    PERMISSIONS.ORGANIZATION_VIEW_SETTINGS,
    PERMISSIONS.ORGANIZATION_UPDATE_SETTINGS,
    PERMISSIONS.ORGANIZATION_VIEW_MEMBERS,
    PERMISSIONS.ORGANIZATION_MANAGE_CUSTOM_ROLES,
    PERMISSIONS.ORGANIZATION_ASSIGN_CUSTOM_ROLES,
    PERMISSIONS.ORGANIZATION_VIEW_AUDIT_LOGS,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_REMOVE,
    PERMISSIONS.MEMBER_UPDATE_ROLE,
    PERMISSIONS.MEMBER_VIEW_PROFILE,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_READ_ALL,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_MANAGE_CATEGORIES,
    PERMISSIONS.PRODUCT_MANAGE_STOCK,
    PERMISSIONS.PRODUCT_VIEW_STOCK_LEVELS,
    PERMISSIONS.SALE_CREATE, // Admins might not do sales, but can oversee
    PERMISSIONS.SALE_READ_ALL,
    PERMISSIONS.SALE_UPDATE,
    PERMISSIONS.SALE_VOID,
    PERMISSIONS.SALE_PROCESS_RETURN,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_READ_ALL,
    PERMISSIONS.PURCHASE_UPDATE_STATUS,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_READ_ALL,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.INVENTORY_LOCATION_CREATE,
    PERMISSIONS.INVENTORY_LOCATION_READ_ALL,
    PERMISSIONS.INVENTORY_LOCATION_UPDATE,
    PERMISSIONS.INVENTORY_LOCATION_DELETE,
    PERMISSIONS.REPORT_VIEW_SALES,
    PERMISSIONS.REPORT_VIEW_INVENTORY,
    PERMISSIONS.REPORT_VIEW_FINANCIAL,
    PERMISSIONS.EXPENSE_READ_ALL,
    PERMISSIONS.EXPENSE_APPROVE, // if admin is an approver
    PERMISSIONS.EXPENSE_MANAGE_CATEGORIES,
    PERMISSIONS.EXPENSE_MANAGE_SETTINGS,
    PERMISSIONS.BUDGET_CREATE,
    PERMISSIONS.BUDGET_READ_ALL,
    PERMISSIONS.BUDGET_UPDATE,
    PERMISSIONS.BUDGET_DELETE,
    PERMISSIONS.ATTENDANCE_VIEW_ALL_LOGS,
    PERMISSIONS.ATTENDANCE_MANAGE_SETTINGS,
    PERMISSIONS.ATTENDANCE_MANUAL_ENTRY,
    PERMISSIONS.ASSISTANT_MANAGE_CONFIGURATION,
    PERMISSIONS.ASSISTANT_VIEW_LOGS,
    PERMISSIONS.CHANNEL_MANAGE_ANY,
    PERMISSIONS.PRINTER_SETTINGS_MANAGE,
    // ... and many more, excluding perhaps direct sales actions if not applicable
  ],
  MANAGER: [
    PERMISSIONS.ORGANIZATION_VIEW_MEMBERS, // View members in their scope
    PERMISSIONS.MEMBER_VIEW_PROFILE,
    PERMISSIONS.PRODUCT_READ_ALL,
    PERMISSIONS.PRODUCT_MANAGE_STOCK,
    PERMISSIONS.PRODUCT_VIEW_STOCK_LEVELS,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.SALE_READ_LOCATION, // Sales in their location/department
    PERMISSIONS.SALE_READ_OWN,
    PERMISSIONS.SALE_UPDATE,
    PERMISSIONS.SALE_PROCESS_RETURN,
    PERMISSIONS.PURCHASE_CREATE, // Or request purchase
    PERMISSIONS.PURCHASE_READ_ALL, // Purchases related to their area
    PERMISSIONS.CUSTOMER_READ_ALL, // Customers they interact with
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.INVENTORY_LOCATION_READ_ALL, // Their assigned locations
    PERMISSIONS.INVENTORY_LOCATION_UPDATE, // Manage their locations
    PERMISSIONS.CASHDRAWER_OPEN,
    PERMISSIONS.CASHDRAWER_CLOSE,
    PERMISSIONS.CASHDRAWER_VIEW_OWN,
    PERMISSIONS.CASHDRAWER_VIEW_ALL, // For reconciliation
    PERMISSIONS.REPORT_VIEW_SALES, // Related to their scope
    PERMISSIONS.REPORT_VIEW_INVENTORY, // Related to their scope
    PERMISSIONS.EXPENSE_CREATE_OWN,
    PERMISSIONS.EXPENSE_CREATE_FOR_OTHERS, // e.g., for their team
    PERMISSIONS.EXPENSE_READ_OWN,
    PERMISSIONS.EXPENSE_READ_TEAM,
    PERMISSIONS.EXPENSE_APPROVE, // If they are designated approvers
    PERMISSIONS.ATTENDANCE_CHECK_IN_OUT_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_OWN_LOGS,
    PERMISSIONS.ATTENDANCE_VIEW_TEAM_LOGS,
    PERMISSIONS.ATTENDANCE_MANUAL_ENTRY, // For their team
    PERMISSIONS.CHANNEL_SEND_MESSAGES,
    // ... more operational permissions
  ],
  EMPLOYEE: [
    PERMISSIONS.MEMBER_UPDATE_OWN_PROFILE,
    PERMISSIONS.PRODUCT_READ_ALL, // To see product details
    PERMISSIONS.PRODUCT_VIEW_STOCK_LEVELS, // To check availability
    PERMISSIONS.SALE_CREATE, // If employee is a salesperson
    PERMISSIONS.SALE_READ_OWN,
    PERMISSIONS.CUSTOMER_CREATE, // If they interact with new customers
    PERMISSIONS.CUSTOMER_READ_ALL, // To find existing customers
    PERMISSIONS.CASHDRAWER_OPEN, // If applicable
    PERMISSIONS.CASHDRAWER_CLOSE, // If applicable
    PERMISSIONS.CASHDRAWER_VIEW_OWN,
    PERMISSIONS.EXPENSE_CREATE_OWN,
    PERMISSIONS.EXPENSE_READ_OWN,
    PERMISSIONS.ATTENDANCE_CHECK_IN_OUT_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_OWN_LOGS,
    PERMISSIONS.CHANNEL_SEND_MESSAGES,
    PERMISSIONS.CHANNEL_JOIN_PUBLIC,
    // ... basic task-oriented permissions
  ],
  CASHIER: [
    PERMISSIONS.MEMBER_UPDATE_OWN_PROFILE,
    PERMISSIONS.PRODUCT_READ_ALL, // To look up products
    PERMISSIONS.PRODUCT_VIEW_STOCK_LEVELS,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.SALE_READ_OWN,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_READ_ALL,
    PERMISSIONS.CASHDRAWER_OPEN,
    PERMISSIONS.CASHDRAWER_CLOSE,
    PERMISSIONS.CASHDRAWER_VIEW_OWN,
    PERMISSIONS.EXPENSE_CREATE_OWN, // e.g. petty cash used
    PERMISSIONS.ATTENDANCE_CHECK_IN_OUT_OWN,
    PERMISSIONS.ATTENDANCE_VIEW_OWN_LOGS,
    PERMISSIONS.CHANNEL_SEND_MESSAGES,
    PERMISSIONS.CHANNEL_JOIN_PUBLIC,
  ],
  REPORTER: [
    PERMISSIONS.ORGANIZATION_VIEW_SETTINGS, // View settings
    PERMISSIONS.ORGANIZATION_VIEW_MEMBERS, // View members list
    PERMISSIONS.MEMBER_VIEW_PROFILE,
    PERMISSIONS.PRODUCT_READ_ALL,
    PERMISSIONS.PRODUCT_VIEW_STOCK_LEVELS,
    PERMISSIONS.SALE_READ_ALL,
    PERMISSIONS.PURCHASE_READ_ALL,
    PERMISSIONS.CUSTOMER_READ_ALL,
    PERMISSIONS.INVENTORY_LOCATION_READ_ALL,
    PERMISSIONS.REPORT_VIEW_SALES,
    PERMISSIONS.REPORT_VIEW_INVENTORY,
    PERMISSIONS.REPORT_VIEW_FINANCIAL,
    PERMISSIONS.EXPENSE_READ_ALL,
    PERMISSIONS.BUDGET_READ_ALL,
    PERMISSIONS.ATTENDANCE_VIEW_ALL_LOGS,
    PERMISSIONS.ASSISTANT_VIEW_LOGS,
    PERMISSIONS.CHANNEL_JOIN_PUBLIC, // Can join to observe/get reports
    // ... view-only permissions
  ],
  CUSTOMER: [
    // This role is on MemberRole enum, but customers usually aren't Members.
    // If they are (e.g. internal staff also being customers of a service), define minimal perms.
    // Typically customer portal access is handled differently.
    PERMISSIONS.MEMBER_UPDATE_OWN_PROFILE,
  ],
  DEVELOPER: [
    // Example: If you have internal developers needing specific access
    PERMISSIONS.ORGANIZATION_VIEW_SETTINGS,
    PERMISSIONS.ORGANIZATION_VIEW_MEMBERS,
    PERMISSIONS.ORGANIZATION_VIEW_AUDIT_LOGS,
    PERMISSIONS.PRODUCT_READ_ALL,
    PERMISSIONS.SALE_READ_ALL,
    // ... etc. This role is often more about system-level access than org-level data manipulation
  ],
};
